name: Go  # The name of the workflow that will appear on Github

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.19]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test ./... -v -coverprofile=coverage.out

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.out

    - name: Generate coverage badge
      run: |
        go install github.com/jpoles1/gopherbadger@latest
        gopherbadger -png=false -md="README.md" -coverfile="coverage.out"

    - name: Commit coverage badge changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout -b update-coverage-badge
        git add README.md
        git commit -m 'Update coverage badge'
        git push -u origin update-coverage-badge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update-coverage-badge
        title: 'Update coverage badge'
        body: 'This PR updates the coverage badge in the README.md'
        labels: ['coverage', 'automated PR']
